# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherMVVMExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'R.swift'
  pod 'Reachability', '~> 3'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'

  target 'WeatherMVVMExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherMVVMExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
